<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class StudentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('students')->insert([
            [
                'name' => 'Nicholas',
                'code'=>'SV0001',
                'email' => 'v@gmail.com',
                'birthday' => new Carbon('first day of January 1999'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Benjamin',
                'code'=>'SV0002',
                'email' => 'Benjamin@gmail.com',
                'birthday' => new Carbon('first day of January 1999'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Ava',
                'code'=>'SV0003',
                'email' => 'Ava@gmail.com',
                'birthday' => new Carbon('first day of January 1954'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Alexander',
                'code'=>'SV0004',
                'email' => 'Jonathan@gmail.com',
                'birthday' => new Carbon('first day of January 1999'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Alexander',
                'code'=>'SV0005',
                'email' => 'Nathan@gmail.com',
                'birthday' => new Carbon('first day of January 1999'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Sophia',
                'code'=>'SV0006',
                'email' => 'Elizabeth@gmail.com',
                'birthday' => new Carbon('first day of January 1999'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Michael',
                'code'=>'SV0007',
                'email' => 'Michael@gmail.com',
                'birthday' => new Carbon('first day of January 1999'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Isabella',
                'code'=>'SV0008',
                'email' => 'Isabella@gmail.com',
                'birthday' => new Carbon('first day of January 1999'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Isabella',
                'code'=>'SV0009',
                'email' => 'Isabella@gmail.com',
                'birthday' => new Carbon('first day of January 1999'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Mia',
                'code'=>'SV0010',
                'email' => 'Mia@gmail.com',
                'birthday' => new Carbon('first day of January 1999'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Daniel',
                'code'=>'SV0011',
                'email' => 'Daniel@gmail.com',
                'birthday' => new Carbon('first day of January 1999'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Charlotte',
                'code'=>'SV0012',
                'email' => 'Charlotte@gmail.com',
                'birthday' => new Carbon('first day of January 1999'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Matthew',
                'code'=>'SV0013',
                'email' => 'Matthew@gmail.com',
                'birthday' => new Carbon('first day of January 1999'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Amelia',
                'code'=>'SV0014',
                'email' => 'Amelia@gmail.com',
                'birthday' => new Carbon('first day of January 1999'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Joseph',
                'code'=>'SV0015',
                'email' => 'Joseph@gmail.com',
                'birthday' => new Carbon('first day of January 1999'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Harper',
                'code'=>'SV0016',
                'email' => 'Harper@gmail.com',
                'birthday' => new Carbon('first day of January 1999'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Samuel',
                'code'=>'SV0017',
                'email' => 'Samuel@gmail.com',
                'birthday' => new Carbon('first day of January 1999'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Evelyn',
                'code'=>'SV0018',
                'email' => 'Evelyn@gmail.com',
                'birthday' => new Carbon('first day of January 1999'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'David',
                'code'=>'SV0019',
                'email' => 'Abigail@gmail.com',
                'birthday' => new Carbon('first day of January 1999'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Andrew',
                'code'=>'SV0020',
                'email' => 'Andrew@gmail.com',
                'birthday' => new Carbon('first day of January 1999'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Emily',
                'code'=>'SV0021',
                'email' => 'Emily@gmail.com',
                'birthday' => new Carbon('first day of January 1999'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Elizabeth',
                'code'=>'SV0022',
                'email' => 'Elizabeth@gmail.com',
                'birthday' => new Carbon('first day of January 1999'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Christopher',
                'code'=>'SV0023',
                'email' => 'Christopher@gmail.com',
                'birthday' => new Carbon('first day of January 1999'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Avery',
                'code'=>'SV0024',
                'email' => 'Avery@gmail.com',
                'birthday' => new Carbon('first day of January 1999'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Ryan',
                'code'=>'SV0025',
                'email' => 'Ryan@gmail.com',
                'birthday' => new Carbon('first day of January 1999'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            
        ]);
    }
}
